title: Codec1 - Tech Blog
Author: Codec1
Description: Codec1 is blog platform where it has various types of programming language blog, tips, code snippet.
description: "Coding tutorials, web development tips, and tech insights."
theme: jekyll-theme-cayman
